# -*- coding: utf-8 -*-
"""Language_translation_tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixNB-UNK-Mu2zYX8_Bg8kjnYf9MZdCg3
"""

!pip install gradio googletrans==4.0.0-rc1

import gradio as gr
from googletrans import Translator

translator = Translator()

languages = {
    "English": "en",
    "Tamil": "ta",
    "Hindi": "hi",
    "French": "fr",
    "German": "de",
    "Spanish": "es",
    "Japanese": "ja",
    "Chinese": "zh-cn",
    "Korean": "ko",
    "Arabic": "ar"
}

def translate_text(text, source_lang, target_lang):
    try:
        result = translator.translate(
            text,
            src=languages[source_lang],
            dest=languages[target_lang]
        )
        return result.text
    except Exception as e:
        return f"Error: {e}"

interface = gr.Interface(
    fn=translate_text,
    inputs=[
        gr.Textbox(label="Enter Text"),
        gr.Dropdown(list(languages.keys()), label="Source Language"),
        gr.Dropdown(list(languages.keys()), label="Target Language")
    ],
    outputs=gr.Textbox(label="Translated Text"),
    title="Language Translation Tool",
    description="Translate text between multiple languages using AI."
)

interface.launch()

with gr.Blocks() as demo:
    gr.Markdown("# Language Translation Tool")

    text = gr.Textbox(label="Enter Text")
    source = gr.Dropdown(list(languages.keys()), label="Source Language")
    target = gr.Dropdown(list(languages.keys()), label="Target Language")

    output = gr.Textbox(label="Translated Text")

    translate_btn = gr.Button("Translate")

    translate_btn.click(
        translate_text,
        inputs=[text, source, target],
        outputs=output
    )

demo.launch()

